### ISSUE TITLE
Session killer issue

### ISSUE THREAD

**Issue by Somebi** [sinterlkaas/YetAnotherRelogger#5]
[10.12.2012 22:49:14] my@mail.com Found login time: 10.12.2012 19:43:50
[10.12.2012 22:49:15] my@mail.com Failed: The remote server returned an error: (500) Internal Server Error.

Session is not killed sometimes. It seems DB server have some problems processing requests sometimes.

Would be nice to set some response code checker, to retry if code is 5xx.

I would gladly help, but i'm not good at c++ etc. ;)

**Comment by Somebi** [comment]
Ok i have looked into sources. I think problem is here:

https://github.com/sinterlkaas/YetAnotherRelogger/blob/master/YetAnotherRelogger/Helpers/BuddyAuth.cs#L149

In my log i haven't seen message "next retry in 5 seconds" so the problem probably is here:

code != HttpStatusCode.InternalServerError

As log says it difinitely was 500 code - "The remote server returned an error: (500) Internal Server Error."

But it's returning somehow.

**Comment by Somebi** [comment]
Ok i just looked into docs. I have added some fixes. Opened pull request.

Here:
https://github.com/sinterlkaas/YetAnotherRelogger/pull/6/files

**Comment by sinterlkaas** [comment]
Hmm yes you indeed pointed me into the right direction I think it should be like this:
if (code != HttpStatusCode.InternalServerError &&
                                code != HttpStatusCode.BadGateway &&
                                code != HttpStatusCode.ServiceUnavailable &&
                                code != HttpStatusCode.GatewayTimeout &&
                                code != HttpStatusCode.RequestTimeout)
                            {
                                Logger.Instance.Write(bot, "Failed: {0}", wex.Message);
                                return;
                            }

PS:
Please push code on my freshly created Experimental branche .. :)

**Comment by sinterlkaas** [comment]
Pushed this part of the code to Experimental thanks for pointing me in the right direction ..
